# Generated by Django 4.0.5 on 2022-07-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pais', models.CharField(max_length=20)),
                ('visita', models.IntegerField()),
                ('idioma', models.CharField(max_length=20)),
            ],
        ),
    ]
