# Generated by Django 4.0.5 on 2022-07-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hotel', models.CharField(max_length=20)),
                ('fecha_apertura', models.DateField()),
                ('ubicacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_aproximado_dolar', models.IntegerField()),
                ('pais_elegido', models.CharField(max_length=20)),
                ('tipo_de_viaje', models.CharField(max_length=20)),
            ],
        ),
    ]
