# Generated by Django 4.0.5 on 2022-07-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_hoteles_viajes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viajes',
            name='presupuesto_aproximado_dolar',
        ),
    ]
