# Generated by Django 4.0.5 on 2022-07-06 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_viajes_presupuesto_aproximado_dolar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteles',
            name='fecha_apertura',
        ),
    ]
