# Generated by Django 4.0.5 on 2022-07-06 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_hoteles_fecha_apertura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='viajes',
        ),
    ]
